### ISSUE TITLE
Forks of 2003page, why we dislike forks.

### ISSUE THREAD

**Issue by PF94** [xporg/2003page.ga#6]
Hello, We have recently noticed that a user called "PedroxTheBest" forked our project. The reason why i find forks to be very unnecessary is that unless if a Pull request was made and then appected, The fork's changes wouldn't apply to 2003page itself.

**Comment by PF94** [comment]
It may be controversal but Pedrox's joining 2003page.

**Comment by AldenBluetenberger** [comment]
Hey, PF94. Maybe... just maybe. They want to make their own version?

**Comment by AldenBluetenberger** [comment]
This isn't even worthy of an issue.

**Comment by PF94** [comment]
> 
> 
> This isn't even worthy of an issue.

Or they're just very lazy and they don't know how to use GitHub?

**Comment by JackGamesFTW** [comment]
hey bb can you block me <3

**Comment by PF94** [comment]
Why do you have a 2nd account? also why you call me "bb"?

**Comment by AldenBluetenberger** [comment]
did you really assume that JackGamesFTW was my alt?

**Comment by PedroxTheBest99** [comment]
fuk you 
![image](https://user-images.githubusercontent.com/48327019/60108666-61bcae80-973f-11e9-8542-d87d9ed9938a.png)

**Comment by PF94** [comment]
Locking conversation to avoid any other drama.
